/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "/home/akash/Documents/DigitalLab/verilog_tasks/mux2to1/source/mux2to1.v:1" *)
module mux2to1(in0, in1, s, out);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "/home/akash/Documents/DigitalLab/verilog_tasks/mux2to1/source/mux2to1.v:3" *)
  input in0;
  (* src = "/home/akash/Documents/DigitalLab/verilog_tasks/mux2to1/source/mux2to1.v:3" *)
  input in1;
  (* src = "/home/akash/Documents/DigitalLab/verilog_tasks/mux2to1/source/mux2to1.v:4" *)
  output out;
  (* src = "/home/akash/Documents/DigitalLab/verilog_tasks/mux2to1/source/mux2to1.v:3" *)
  input s;
  INVX1 _3_ (
    .A(in0),
    .Y(_0_)
  );
  NAND2X1 _4_ (
    .A(in1),
    .B(s),
    .Y(_1_)
  );
  OAI21X1 _5_ (
    .A(s),
    .B(_0_),
    .C(_1_),
    .Y(_2_)
  );
  (* keep = 32'd1 *)
  BUFX2 _6_ (
    .A(_2_),
    .Y(out)
  );
endmodule
